/**
 * Watermark module — XOR-encrypted author credit.
 * The plain-text name is never stored in source; it's decrypted at runtime
 * and injected into generated documentation during the Sphinx build.
 *
 * If you fork wiki-gen, change ENCRYPTED_WATERMARK and WATERMARK_KEY below
 * to your own encrypted name. The decryptWatermark function will still work.
 * MIT License requires attribution preservation — don't remove this module.
 */

const WATERMARK_KEY = "wiki-gen-runtime-seal-v1"

// XOR-encrypted author name as hex. Change this to your own encrypted name.
const ENCRYPTED_WATERMARK = "25080c01580b453c"

/**
 * Decrypt the watermark at runtime. Returns the plain-text author name.
 */
export function watermark(): string {
  return xorDecrypt(ENCRYPTED_WATERMARK, WATERMARK_KEY)
}

/**
 * Full credit line for generated documentation.
 */
export function watermarkCredit(): string {
  return `Documentation generated by wiki-gen by ${watermark()}`
}

/**
 * Short inline credit.
 */
export function watermarkInline(): string {
  return `Generated by wiki-gen · Created by ${watermark()}`
}

/**
 * Encrypt a name for storage. Use this to generate your own ENCRYPTED_WATERMARK
 * if you fork the project.
 *
 * Usage: node -e "const {encryptName} = require('./dist/watermark.js'); console.log(encryptName('Your Name'));"
 */
export function encryptName(name: string): string {
  return xorEncrypt(name, WATERMARK_KEY)
}

// ── XOR cipher helpers (pure JS, no external deps) ──────────────────────

function xorEncrypt(text: string, key: string): string {
  const buf = Buffer.alloc(text.length)
  for (let i = 0; i < text.length; i++) {
    buf[i] = text.charCodeAt(i) ^ key.charCodeAt(i % key.length)
  }
  return buf.toString("hex")
}

function xorDecrypt(hex: string, key: string): string {
  const bytes = Buffer.from(hex, "hex")
  let result = ""
  for (let i = 0; i < bytes.length; i++) {
    result += String.fromCharCode(bytes[i] ^ key.charCodeAt(i % key.length))
  }
  return result
}
